use_frameworks!

target 'ylpodtest_Example' do
  pod 'ylpodtest', :path => '../'

  target 'ylpodtest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
